@startuml class

class userManager {
    email
    password
    +login()
    +logout()

}

class bookProvider {
    book_title
    author
    publisher
    isbn_10
    isbn_13
    image_uml
    -convert_parameter()
    +index()
    +create()
    +show()
    +search()
    +edit()
    +destroy()
}

class commentProvider {
    comment
    +create()
    +find()
    +edit()
    +destroy()
}

userManager "1" o-right- "1..*" bookProvider : 書籍
bookProvider "1" o-right- "0..*" commentProvider : コメント

@enduml