@startuml database
package 蔵書データベース <<Database>> {
  entity users {
    + id
    --
    email
    password
    admin
    ..
    created_at
    updated_at

  }
  entity libraries {
    + id
    --
    book_title
    author
    publisher
    image_url
    * user_id
    ..
    created_at
    updated_at
  }
  entity comments {
    + id
    --
    comment
    * book_id
    ..
    created_at
    updated_at
  }
}
users -ri-|{ libraries : 1 .. n
libraries -ri-|{ comments : 1 .. n
@enduml