@startuml database
package database <<Database>> {
  entity libraries {
    + id
    --
    book_title
    author
    publisher
    image_url
    ..
    created_at
    updated_at
  }
  entity comments {
    + id
    --
    comment
    * book_id
    ..
    created_at
    updated_at
  }
}
libraries -ri-|{ comments : 本のメモ >
@enduml