@startuml
title ユースケース図

actor 利用者
left to right direction

rectangle 蔵書管理 {
    package 本の管理 {
        利用者 -> (蔵書の一覧を表示する)
        利用者 --> (蔵書を登録する)
        利用者 --> (蔵書を編集する)
        利用者 --> (蔵書を削除する)
        (蔵書の一覧を表示する) ..> (蔵書を表示する) : include
        (蔵書を編集する) ..> (蔵書を表示する) : include
        (蔵書を削除する) ..> (蔵書を表示する) : include
    }
    package コメント {
        利用者 --> (コメントを追記する)
        利用者 --> (コメントを削除する)
        (コメントを削除する) ..> (コメントを表示する) : include
    }
}
@enduml